//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoWHeadParser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WoWHeadParser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 476;114
        ///477;118
        ///478;116
        ///479;1179
        ///481;6148
        ///483;143
        ///484;7300
        ///485;113
        ///486;475
        ///487;246
        ///488;131
        ///490;6134
        ///493;491
        ///494;205
        ///495;851
        ///496;5138
        ///497;122
        ///499;768
        ///502;145
        ///504;5599
        ///506;7302
        ///517;1953
        ///519;5388
        ///520;512
        ///521;8929
        ///531;529
        ///532;324
        ///533;344
        ///534;315
        ///535;6229
        ///536;526
        ///537;365
        ///538;332
        ///539;8924
        ///540;528
        ///541;2866
        ///557;325
        ///558;370
        ///559;5615
        ///560;544
        ///561;545
        ///562;546
        ///563;8928
        ///565;547
        ///566;548
        ///567;549
        ///569;550
        ///570;6196
        ///571;552
        ///573;8925
        ///574;5592
        ///575;554
        ///577;556
        ///607;17951
        ///608;58 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TrainerSpells {
            get {
                return ResourceManager.GetString("TrainerSpells", resourceCulture);
            }
        }
    }
}
